"""Public pytest-benchmark matrix and JSON results API."""

from importlib.metadata import PackageNotFoundError, version

from ._schema import MetricName
from .bench_collection import (
    BenchmarkPairedRunGroup,
    BenchmarkPairedRunRecord,
    BenchmarkPairSchedule,
    BenchmarkRunGroup,
    BenchmarkRunPair,
    BenchmarkRunRecord,
    balanced_cell_order,
    balanced_order_cycle_length,
    balanced_order_supercycle_length,
    collect_benchmark_runs,
    collect_paired_benchmark_runs,
    load_benchmark_run_group,
    load_paired_benchmark_run_group,
    make_paired_ab_ba_schedule,
)
from .bench_compare import (
    BenchmarkComparison,
    BenchmarkEvidence,
    BenchmarkInference,
    BenchmarkRunComparison,
    EvidencePolicy,
    InferencePolicy,
    PrecisionPolicy,
    RegressionPolicy,
    RunCompatibilityFinding,
    RunCompatibilityPolicy,
    RunCompatibilityReport,
    compare_benchmark_run_groups,
    compare_benchmark_runs,
    compare_paired_benchmark_run_groups,
)
from .bench_harness import (
    BenchmarkCase,
    BenchmarkConfig,
    BenchmarkFixture,
    BenchmarkHookContext,
    BenchmarkInvocationRecord,
    BenchmarkLifecycleHook,
    BenchmarkResultValidator,
    TargetFunction,
    benchmark_batch_throughput,
    benchmark_single_call_latency,
    benchmark_tail_latency,
    deep_copy,
    make_benchmark_parameters,
    make_benchmark_test,
    run_benchmark_metric,
    shallow_copy,
)
from .bench_policy import BenchmarkPolicyConfig, default_benchmark_policy, load_benchmark_policy
from .bench_report import (
    BenchmarkCollectionSnapshot,
    BenchmarkComparisonReport,
    BenchmarkPairedCollectionSnapshot,
    BenchmarkPolicyProvenance,
    BenchmarkThresholdProvenance,
    format_comparison_report_markdown,
    load_comparison_report,
    write_comparison_report,
    write_comparison_report_markdown,
)
from .bench_results import (
    BenchmarkRun,
    ParsedBenchmarkRow,
    display_benchmark_row,
    display_benchmark_rows,
    load_benchmark_json,
    load_benchmark_run,
)
from .bench_statistics import PrecisionPlan, plan_paired_precision
from .exceptions import (
    BenchmarkCollectionError,
    BenchmarkJsonError,
    BenchmarkPolicyError,
    BenchmatrixError,
    MetadataSerializationError,
)

try:
    __version__ = version("benchmatrix")
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"

__all__ = [
    "BenchmarkCase",
    "BenchmarkCollectionError",
    "BenchmarkCollectionSnapshot",
    "BenchmarkComparison",
    "BenchmarkComparisonReport",
    "BenchmarkConfig",
    "BenchmarkEvidence",
    "BenchmarkFixture",
    "BenchmarkHookContext",
    "BenchmarkInference",
    "BenchmarkInvocationRecord",
    "BenchmarkJsonError",
    "BenchmarkLifecycleHook",
    "BenchmarkPairSchedule",
    "BenchmarkPairedCollectionSnapshot",
    "BenchmarkPairedRunGroup",
    "BenchmarkPairedRunRecord",
    "BenchmarkPolicyConfig",
    "BenchmarkPolicyError",
    "BenchmarkPolicyProvenance",
    "BenchmarkResultValidator",
    "BenchmarkRun",
    "BenchmarkRunComparison",
    "BenchmarkRunGroup",
    "BenchmarkRunPair",
    "BenchmarkRunRecord",
    "BenchmarkThresholdProvenance",
    "BenchmatrixError",
    "EvidencePolicy",
    "InferencePolicy",
    "MetadataSerializationError",
    "MetricName",
    "ParsedBenchmarkRow",
    "PrecisionPlan",
    "PrecisionPolicy",
    "RegressionPolicy",
    "RunCompatibilityFinding",
    "RunCompatibilityPolicy",
    "RunCompatibilityReport",
    "TargetFunction",
    "__version__",
    "balanced_cell_order",
    "balanced_order_cycle_length",
    "balanced_order_supercycle_length",
    "benchmark_batch_throughput",
    "benchmark_single_call_latency",
    "benchmark_tail_latency",
    "collect_benchmark_runs",
    "collect_paired_benchmark_runs",
    "compare_benchmark_run_groups",
    "compare_benchmark_runs",
    "compare_paired_benchmark_run_groups",
    "deep_copy",
    "default_benchmark_policy",
    "display_benchmark_row",
    "display_benchmark_rows",
    "format_comparison_report_markdown",
    "load_benchmark_json",
    "load_benchmark_policy",
    "load_benchmark_run",
    "load_benchmark_run_group",
    "load_comparison_report",
    "load_paired_benchmark_run_group",
    "make_benchmark_parameters",
    "make_benchmark_test",
    "make_paired_ab_ba_schedule",
    "plan_paired_precision",
    "run_benchmark_metric",
    "shallow_copy",
    "write_comparison_report",
    "write_comparison_report_markdown",
]
